### PR TITLE
Replace CRM_Core_Error::fatal fn

### PR DESCRIPTION
**Pull request by monishdeb**

### CODE REVIEW

**Comment by seamuslee001** [comment]
@monishdeb is there any reason why you didn't just do `civix generate:module` and committed the results that way?

**Comment by monishdeb** [comment]
@seamuslee001  I wasn't sure if it would break anything, is it the case? If not, let me update the PRs then.

**Comment by monishdeb** [comment]
Updated the PR with newly updated civix file.

**Comment by seamuslee001** [comment]
@monishdeb can you re-run civix here looks like the CRM_Core_Error is still present

**Comment by monishdeb** [comment]
> @monishdeb can you re-run civix here looks like the CRM_Core_Error is still present

@seamuslee001 Done

**Comment by seamuslee001** [comment]
changes look fine to me merging

**Pull request merged**
